# Generated by Django 5.1.3 on 2024-12-06 07:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("youtube", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="youtubevideo",
            name="channel_name",
        ),
        migrations.RemoveField(
            model_name="youtubevideo",
            name="likes",
        ),
        migrations.RemoveField(
            model_name="youtubevideo",
            name="video_link",
        ),
        migrations.RemoveField(
            model_name="youtubevideo",
            name="views",
        ),
        migrations.RemoveField(
            model_name="youtubevideo",
            name="views_per_like",
        ),
        migrations.AddField(
            model_name="youtubevideo",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="youtubevideo",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="youtubevideo",
            name="like_count",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="youtubevideo",
            name="tag",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NEGATIVE", "NEGATIVE"),
                    ("NEUTRAL", "NEUTRAL"),
                    ("POSITIVE", "POSITIVE"),
                ],
                max_length=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="youtubevideo",
            name="url",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="youtubevideo",
            name="view_count",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="youtubevideo",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="youtubevideo",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
