# Generated by Django 5.1.3 on 2024-12-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("youtube", "0002_remove_youtubevideo_channel_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="youtubevideo",
            name="description",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
